### PR TITLE
+ * [Radzählstellen in Berlin](https://daten.berlin.de/datensaetze/ra…

### PR DESCRIPTION
**Pull request by Wikinaut**
…dz%C3%A4hldaten-berlin)

### CODE REVIEW

**Comment by ulid000** [comment]
Could you please add the link to the open data portal to the already existing entry "Bike Counters" above in the same section.

**Comment by Wikinaut** [comment]
> Could you please add the link to the open data portal to the already existing entry "Bike Counters" above in the same section.

Do you mean "move" or "add"?

**Comment by ulid000** [comment]
"move" in the context of the PR, "add" in the context of the list before the PR ;-)

**Comment by mltbnz** [comment]
Now it works 👍

**Pull request merged**
